# Generated by Django 3.1 on 2020-09-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('task_describtion', models.TextField()),
                ('task_duration', models.DateTimeField(verbose_name='Date of Complition')),
            ],
        ),
    ]
