# Generated by Django 3.1 on 2020-09-16 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_category', models.CharField(max_length=200)),
                ('catagory_summery', models.CharField(max_length=200)),
                ('category_slug', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.CreateModel(
            name='CheckPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_checkpoint', models.CharField(max_length=200)),
                ('checkpoint_content', models.CharField(max_length=200)),
                ('checkpoint_slug', models.CharField(max_length=200)),
                ('task_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.taskcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Checkpoints',
            },
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_checkpoint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.checkpoints', verbose_name='Checkpoint'),
        ),
    ]
